### PR TITLE
Remove extra space in list item

### LINKED ISSUE #903: HTML to Markdown is wrong for lists of lists
As found in https://github.com/OpenTermsArchive/p2b-compliance-declarations/pull/113

lists are translated incorrectly and give

```
6.  **chapter 6**.
    
    1.  **subchapter i**. looks ok ...
        
7.  **Chapter 7**. with no subchapter seems ok too
        
8.  **Chapter 8**.
    
    1.  **Entire Agreement**. still ok

9.  **Chapter 9**.
    
    1.  **Entire Agreement**. still ok

10.  **Chapter 10**.
    
    1.  **Entire Agreement**. not ok anymore
 
11.  **Chapter 11**.
    
    1.  **Entire Agreement**. not ok anymore
```

instead of 
```
6.  **chapter 6**.
    
    1.  **subchapter i**. looks ok ...
        
7.  **Chapter 7**. with no subchapter seems ok too
        
8.  **Chapter 8**.
    
    1.  **Entire Agreement**. still ok

9.  **Chapter 9**.
    
    1.  **Entire Agreement**. still ok

10. **Chapter 10**.
    
    1.  **Entire Agreement**. not ok anymore
 
11. **Chapter 11**.
    
    1.  **Entire Agreement**. not ok anymore
```

(Note the additional space after `10.` and `11.`

You can retrieve the problematic html with

```
wget https://www.mturk.com/participation-agreement -O participation-agreement.html
```

### PR DESCRIPTION
**Pull request by Ndpnt**
Fixes https://github.com/ambanum/OpenTermsArchive/issues/903

### CODE REVIEW

File: src/commonmark-rules.js [hunk 1]
```diff
@@ -66,12 +66,12 @@ rules.listItem = {
...
       .replace(/\n+$/, '\n') // replace trailing newlines with just a single one
       .replace(/\n/gm, '\n    ') // indent
-    var prefix = options.bulletListMarker + '   '
+    var prefix = options.bulletListMarker + ' '
     var parent = node.parentNode
     if (parent.nodeName === 'OL') {
       var start = parent.getAttribute('start')
       var index = Array.prototype.indexOf.call(parent.children, node)
-      prefix = (start ? Number(start) + index : index + 1) + '.  '
+      prefix = (start ? Number(start) + index : index + 1) + '. '
```
Comment (martinratinaud) [inline src/commonmark-rules.js:74]: I think it would be easier to use 

```
prefix = `${start.padEnd(3)}.`
```

```
> "1".padEnd(3)
'1  '
> 12".padEnd(3)
'12 '
> "123".padEnd(3)
'123'
```

**Review by martinratinaud — CHANGES_REQUESTED** [review]
I suggest to use `padEnd` function

File: src/commonmark-rules.js (hunk 1 above)
Comment (Ndpnt) [reply src/commonmark-rules.js:74]: Let's make minimal changes to the original codebase to make it easier to switch back to the original repo if the author returns or if we choose to use another fork.

**Review by martinratinaud — APPROVED** [review]

**Review by martinratinaud — APPROVED** [review]
